java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/8-machines/random/output-scc-1.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/8-machines/random/output-scc-1-reformatted.txt
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/8-machines/cluster/output-scc-1.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/8-machines/cluster/output-scc-1-reformatted.txt  
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/8-machines/balanced/output-scc-5.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/8-machines/balanced/output-scc-5-reformatted.txt 
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/8-machines/balanced/output-scc-6.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/8-machines/balanced/output-scc-6-reformatted.txt 

java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/16-machines/random/output-scc-1.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/16-machines/random/output-scc-1-reformatted.txt
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/16-machines/cluster/output-scc-1.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/16-machines/cluster/output-scc-1-reformatted.txt  
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/16-machines/balanced/output-scc-5.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/16-machines/balanced/output-scc-5-reformatted.txt 
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/16-machines/balanced/output-scc-6.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/16-machines/balanced/output-scc-6-reformatted.txt 

java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/32-machines/random/output-scc-1.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/32-machines/random/output-scc-1-reformatted.txt
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/32-machines/cluster/output-scc-1.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/32-machines/cluster/output-scc-1-reformatted.txt  
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/32-machines/balanced/output-scc-5.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/32-machines/balanced/output-scc-5-reformatted.txt 
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/32-machines/balanced/output-scc-6.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/32-machines/balanced/output-scc-6-reformatted.txt 

java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/64-machines/random/output-scc-1.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/64-machines/random/output-scc-1-reformatted.txt
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/64-machines/cluster/output-scc-1.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/64-machines/cluster/output-scc-1-reformatted.txt  
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/64-machines/balanced/output-scc-5.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/64-machines/balanced/output-scc-5-reformatted.txt 
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/64-machines/balanced/output-scc-6.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/64-machines/balanced/output-scc-6-reformatted.txt 

java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/128-machines/random/output-scc-1.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/128-machines/random/output-scc-1-reformatted.txt
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/128-machines/cluster/output-scc-1.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/128-machines/cluster/output-scc-1-reformatted.txt  
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/128-machines/balanced/output-scc-5.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/128-machines/balanced/output-scc-5-reformatted.txt 
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/128-machines/balanced/output-scc-6.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/128-machines/balanced/output-scc-6-reformatted.txt 

java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/8-machines/random/output-scc-dynamic-1.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/8-machines/random/output-scc-dynamic-1-reformatted.txt
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/8-machines/cluster/output-scc-dynamic-1.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/8-machines/cluster/output-scc-dynamic-1-reformatted.txt  
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/8-machines/balanced/output-scc-dynamic-5.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/8-machines/balanced/output-scc-dynamic-5-reformatted.txt 
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/8-machines/balanced/output-scc-dynamic-6.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/8-machines/balanced/output-scc-dynamic-6-reformatted.txt 

java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/16-machines/random/output-scc-dynamic-1.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/16-machines/random/output-scc-dynamic-1-reformatted.txt
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/16-machines/cluster/output-scc-dynamic-1.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/16-machines/cluster/output-scc-dynamic-1-reformatted.txt  
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/16-machines/balanced/output-scc-dynamic-5.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/16-machines/balanced/output-scc-dynamic-5-reformatted.txt 
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/16-machines/balanced/output-scc-dynamic-6.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/16-machines/balanced/output-scc-dynamic-6-reformatted.txt 

java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/32-machines/random/output-scc-dynamic-1.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/32-machines/random/output-scc-dynamic-1-reformatted.txt
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/32-machines/cluster/output-scc-dynamic-1.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/32-machines/cluster/output-scc-dynamic-1-reformatted.txt  
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/32-machines/balanced/output-scc-dynamic-5.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/32-machines/balanced/output-scc-dynamic-5-reformatted.txt 
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/32-machines/balanced/output-scc-dynamic-6.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/32-machines/balanced/output-scc-dynamic-6-reformatted.txt 

java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/64-machines/random/output-scc-dynamic-1.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/64-machines/random/output-scc-dynamic-1-reformatted.txt
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/64-machines/cluster/output-scc-dynamic-1.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/64-machines/cluster/output-scc-dynamic-1-reformatted.txt  
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/64-machines/balanced/output-scc-dynamic-5.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/64-machines/balanced/output-scc-dynamic-5-reformatted.txt 
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/64-machines/balanced/output-scc-dynamic-6.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/64-machines/balanced/output-scc-dynamic-6-reformatted.txt 

java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/128-machines/random/output-scc-dynamic-1.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/128-machines/random/output-scc-dynamic-1-reformatted.txt
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/128-machines/cluster/output-scc-dynamic-1.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/128-machines/cluster/output-scc-dynamic-1-reformatted.txt  
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/128-machines/balanced/output-scc-dynamic-5.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/128-machines/balanced/output-scc-dynamic-5-reformatted.txt 
java ReformatOutputFiles /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/128-machines/balanced/output-scc-dynamic-6.txt  /Users/semihsalihoglu/projects/pregel/output/simulation_results/email-EuAll/128-machines/balanced/output-scc-dynamic-6-reformatted.txt 